# Generated by Django 3.2 on 2022-05-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('CUSTOMER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CUSTOMER_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('CONTACT_PERSON', models.CharField(blank=True, max_length=50, null=True)),
                ('PRESENT_ADDRESS', models.TextField(blank=True, null=True)),
                ('TEL', models.CharField(blank=True, max_length=50, null=True)),
                ('MOB', models.CharField(blank=True, max_length=50, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=50, null=True)),
                ('DOT', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSTOMER_PIC', models.ImageField(blank=True, null=True, upload_to='')),
                ('USER_ID', models.BigIntegerField(blank=True, null=True)),
                ('ZONE_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('RECEIVABLE_ACCOUNT_CODE', models.BigIntegerField(blank=True, null=True)),
                ('CLIENT_LEVEL', models.CharField(blank=True, max_length=25, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=15, null=True)),
                ('REP_CODE', models.BigIntegerField(blank=True, null=True)),
                ('CUST_CAT', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
