# Generated by Django 3.2 on 2022-06-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_detail',
            table='CUSTOMER_DETAILS',
        ),
    ]
