# Generated by Django 3.2 on 2022-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_detail_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_detail',
            name='CUSTOMER_ID',
            field=models.BinaryField(max_length='max', primary_key=True, serialize=False),
        ),
    ]
