# Generated by Django 3.2 on 2022-05-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220527_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
