# Generated by Django 3.2 on 2022-06-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customer_detail_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='ADV_ACCOUNT_CODE',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='CREDIT_LIMIT',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='DOT',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
