# Generated by Django 3.2 on 2022-06-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220604_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_detail',
            name='ADV_ACCOUNT_CODE',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='CLIENT_LEVEL',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='CONTACT_PERSON',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='CREDIT_LIMIT',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='CUSTOMER_NAME',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='CUSTOMER_PIC',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='CUST_CAT',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='DOT',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='EMAIL',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='MOB',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='PRESENT_ADDRESS',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='RECEIVABLE_ACCOUNT_CODE',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='REP_CODE',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='STATUS',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='TEL',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='ZONE_CODE',
        ),
    ]
