# Generated by Django 3.2 on 2022-06-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220604_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='CUSTOMER_NAME',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
