# Generated by Django 3.2 on 2022-06-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customer_detail_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='CONTACT_PERSON',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
