# Generated by Django 3.2 on 2022-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220604_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='CUSTOMER_PIC',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
