# Generated by Django 3.2 on 2022-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customer_detail_customer_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_detail',
            name='CUSTOMER_PIC',
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='ADV_ACCOUNT_CODE',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='CLIENT_LEVEL',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='CREDIT_LIMIT',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='CUST_CAT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='RECEIVABLE_ACCOUNT_CODE',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='REP_CODE',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='STATUS',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='USER_ID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='ZONE_CODE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
