# Generated by Django 3.2 on 2022-06-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220604_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='CUSTOMER_PIC',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
