# Generated by Django 3.2 on 2022-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customer_detail_customer_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='LATITUDE',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='LOGITUDE',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
