# Generated by Django 3.2 on 2022-06-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220605_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOMER_CATEGORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAT_ID', models.BigIntegerField(blank=True, null=True)),
                ('CUST_CAT', models.CharField(blank=True, max_length=50, null=True)),
                ('MAX_DISCRATE', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CUSTOMER_CATEGORY',
            },
        ),
    ]
