# Generated by Django 3.2 on 2022-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_customer_detail_customer_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='CUSTOMER_PIC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
