# Generated by Django 3.2 on 2022-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customer_detail_customer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_detail',
            name='CUSTOMER_PIC',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
    ]
