# Generated by Django 3.2 on 2022-06-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('USER_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('USER_NAME', models.CharField(max_length=50)),
                ('LOGIN_NAME', models.CharField(max_length=50)),
                ('PASSWORD', models.TextField()),
                ('SWAP_CARD', models.CharField(max_length=50)),
                ('ACCESS_LEVEL', models.CharField(max_length=50)),
                ('REG_DATE', models.DateTimeField(auto_now_add=True)),
                ('STATUS', models.CharField(max_length=50)),
                ('CREATED_BY', models.BigIntegerField()),
            ],
            options={
                'db_table': 'USER_ACCOUNT',
            },
        ),
    ]
