# Generated by Django 3.2 on 2022-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_useraccount_job_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='JOB_TITLE_ID',
            field=models.BigIntegerField(),
        ),
    ]
