# Generated by Django 3.2 on 2022-05-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORDER_DETAILS',
            fields=[
                ('ORDER_TRANSAC_SL', models.AutoField(primary_key=True, serialize=False)),
                ('ORDER_NO', models.BigIntegerField(blank=True, null=True)),
                ('PROD_CODE', models.BigIntegerField(blank=True, null=True)),
                ('RATE', models.IntegerField(blank=True, null=True)),
                ('QTY', models.DecimalField(decimal_places=4, max_digits=18)),
                ('ITEM_PRICE', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='ORDER_MASTER',
            fields=[
                ('ORDER_NO', models.AutoField(primary_key=True, serialize=False)),
                ('CUSTOMER_ID', models.BigIntegerField(blank=True, null=True)),
                ('LATITUDE', models.DecimalField(decimal_places=6, max_digits=18)),
                ('LOGITUDE', models.DecimalField(decimal_places=6, max_digits=18)),
                ('USER_ID', models.BigIntegerField(blank=True, null=True)),
                ('STATUS', models.CharField(max_length=25)),
                ('ORDERDETAILS', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
