# Generated by Django 3.2 on 2022-06-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order_details',
            table='ORDER_DETAILS',
        ),
    ]
