# Generated by Django 3.2 on 2022-05-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220529_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_master',
            name='DOT',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
