# Generated by Django 3.2 on 2022-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_details_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='PROD_CODE',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
