# Generated by Django 3.2 on 2022-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_details_prod_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RETURN_REQ_MASTER',
            fields=[
                ('RETURN_NO', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('DOR', models.DateTimeField(auto_now_add=True, null=True)),
                ('ORDER_NO', models.BigIntegerField(blank=True, null=True)),
                ('CUSTOMER_ID', models.IntegerField(blank=True, null=True)),
                ('TOTAL_AMOUNT', models.FloatField(blank=True, null=True)),
                ('STATUS', models.CharField(default='PENDING', max_length=25)),
            ],
        ),
    ]
