# Generated by Django 3.2 on 2022-06-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_return_req_master'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='return_req_master',
            table='RETURN_REQ_MASTER',
        ),
    ]
