# Generated by Django 3.2 on 2022-06-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_return_req_master_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RETURN_REQ_DETAILS',
            fields=[
                ('ORDER_TRANSAC_SL', models.IntegerField(primary_key=True, serialize=False)),
                ('ORDER_NO', models.BigIntegerField(blank=True, null=True)),
                ('PROD_CODE', models.BigIntegerField(blank=True, null=True)),
                ('RATE', models.IntegerField(blank=True, null=True)),
                ('QTY', models.DecimalField(decimal_places=4, max_digits=18)),
                ('ITEM_PRICE', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'RETURN_REQ_DETAILS',
            },
        ),
    ]
