# Generated by Django 3.2 on 2022-06-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_return_req_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='RATE',
            field=models.DecimalField(decimal_places=4, default=1.2, max_digits=18),
            preserve_default=False,
        ),
    ]
