# Generated by Django 3.2 on 2022-06-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_details_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='ORDER_TRANSAC_SL',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
