# Generated by Django 3.2 on 2022-06-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220603_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_req_details',
            name='ORDER_TRANSAC_SL',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
