# Generated by Django 3.2 on 2022-06-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_return_req_details_order_transac_sl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return_req_details',
            old_name='ORDER_NO',
            new_name='RETURN_NO',
        ),
    ]
