# Generated by Django 3.2 on 2022-06-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_order_no_return_req_details_return_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return_req_details',
            old_name='ORDER_TRANSAC_SL',
            new_name='RETURN_TRANSAC_SL',
        ),
    ]
