# Generated by Django 3.2 on 2022-06-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_order_transac_sl_return_req_details_return_transac_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='RATE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
