# Generated by Django 3.2 on 2022-06-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_details_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='RATE',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='return_req_details',
            name='RATE',
            field=models.DecimalField(decimal_places=4, default=34.0, max_digits=18),
            preserve_default=False,
        ),
    ]
