# Generated by Django 3.2 on 2022-06-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220605_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_master',
            name='TOTAL_AMOUNT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
