# Generated by Django 3.2 on 2022-06-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product_master',
            table='PRODUCT_MASTER',
        ),
    ]
