# Generated by Django 3.2 on 2022-06-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220604_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_master',
            old_name='UNIT',
            new_name='COLOUR',
        ),
    ]
