# Generated by Django 3.2 on 2022-06-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_unit_product_master_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCT_MASTER_1',
            fields=[
                ('PROD_CODE_SL', models.BigIntegerField(primary_key=True, serialize=False)),
                ('PROD_CODE', models.BigIntegerField(blank=True, null=True)),
                ('PROD_DESC', models.TextField(blank=True, null=True)),
                ('BARCODE', models.CharField(blank=True, max_length=50, null=True)),
                ('GROUP_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('PRODUCT_LINE_CODE', models.TextField(blank=True, null=True)),
                ('SUPPLIER_CODE', models.BigIntegerField(blank=True, null=True)),
                ('BRAND', models.CharField(blank=True, max_length=50, null=True)),
                ('MANUFACTURER_CODE', models.BigIntegerField(blank=True, null=True)),
                ('PRODUCT_SIZE', models.CharField(blank=True, max_length=50, null=True)),
                ('UNIT', models.CharField(blank=True, max_length=50, null=True)),
                ('MEASURE_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('AVERAGE_COST', models.FloatField(blank=True, null=True)),
                ('STANDARD_COST', models.FloatField(blank=True, null=True)),
                ('LAST_COST', models.FloatField(blank=True, null=True)),
                ('SALES_RATE', models.FloatField(blank=True, null=True)),
                ('TAXCODE', models.CharField(blank=True, max_length=20, null=True)),
                ('DISCOUNT_CODE', models.BigIntegerField(blank=True, null=True)),
                ('MAX_STOCK', models.IntegerField(blank=True, null=True)),
                ('MIN_STOCK', models.IntegerField(blank=True, null=True)),
                ('PRODUCT_IMAGE', models.ImageField(blank=True, null=True, upload_to='')),
                ('USER_ID', models.BigIntegerField(blank=True, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=50, null=True)),
                ('WARRANTY_DURATION', models.BigIntegerField(blank=True, null=True)),
                ('WARRANTY_DURATION_TYPE', models.CharField(blank=True, max_length=15, null=True)),
                ('INVENTORY_FLAG', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PRODUCT_MASTER-1',
            },
        ),
    ]
