# Generated by Django 3.2 on 2022-06-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_master_1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product_master_1',
            table='PRODUCT_MASTER_1',
        ),
    ]
