# Generated by Django 3.2 on 2022-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_master_1_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_master_1',
            name='PRODUCT_IMAGE',
            field=models.Field(blank=True, null=True),
        ),
    ]
