# Generated by Django 3.2 on 2022-06-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_master_1_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_master_1',
            name='PRODUCT_IMAGE',
        ),
    ]
