# Generated by Django 3.2 on 2022-06-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_master_1_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_master_1',
            name='PROD_CODE',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
