# Generated by Django 3.2 on 2022-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_master_1_prod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_master_1',
            name='PRODUCT_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
