# Generated by Django 3.2 on 2022-06-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_master_1_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_master_1',
            name='PRODUCT_IMAGE',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
    ]
